---
- hosts: sakura
  become: yes
  remote_user: ansible
  vars:
    users:
      - { name: foo }
      - { name: bar }
      - { name: baz }
    ssh_port: 22
    before_ssh_port: 変更後のSSHポート番号★
  tasks:
  - name: ping で疎通確認
    ping:

  - name: ユーザを削除する
    user:
      state=absent
      remove=yes
      name="{{ item.name }}"
    with_items: "{{ users }}"

  - name: オリジナル ssh ポート番号閉塞解除
    firewalld: service=ssh permanent=true state=enabled immediate=yes

  - name: wheelグループからsudo権限を削除する
    lineinfile:
      dest: /etc/sudoers
      regexp: "^%wheel\\s+ALL=\\(ALL\\)\\s+ALL"
      line: "# %wheel ALL=(ALL) ALL"
      backrefs: yes
      validate: "visudo -cf %s"
      backup: yes

  - name: rootユーザでのssh接続を許可する
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin no"
      line: "#PermitRootLogin yes"
      backrefs: yes
      validate: "sshd -T -f %s"
      backup: yes

  - name: ssh ポート番号の復元
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: absent
      regexp: "^Port"
      validate: "sshd -T -f %s"
      backup: yes

  - name: sshd サービス再起動
    service: name=sshd state=restarted

  - name: Ansible で接続するための ssh ポート番号変数変更
    set_fact: ansible_ssh_port={{ ssh_port }}

  - name: iptables の ssh ポート削除
    firewalld: port={{ before_ssh_port }}/tcp permanent=true state=disabled immediate=yes

  handlers:
    - name: restart sshd
      service: name=sshd state=restarted

